### ISSUE TITLE
Failed to initialize OpenGL

### ISSUE THREAD

**Issue by leeivan1007** [avisingh599/reward-learning-rl#1]
I find this but didn't help for me... 
[https://github.com/openai/mujoco-py/issues/187](url)
My devire is ubuntu16, and has run FetchPickAndPlace-v1 from (penai/baselines) then it can run with env(softlearning)

> Using seed 8179
2019-05-02 18:19:51.057481: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Registering multiworld mujoco gym environments
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-390', '/usr/lib/nvidia-396']
Choosing the latest nvidia driver: /usr/lib/nvidia-396, among ['/usr/lib/nvidia-390', '/usr/lib/nvidia-396']
/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Registering goal example multiworld mujoco gym environments
Found 2 GPUs for rendering. Using device 0.
2019-05-02 18:19:53,330	ERROR trial_runner.py:412 -- Error processing event.
Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 378, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 228, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/worker.py", line 2211, in get
    raise value
ray.worker.RayTaskError: ray_ExperimentRunnerClassifierRL:train() (pid=6795, host=ivan-All-Series-Invalid-entry-length-16-Fixed-up-to-11)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/ivan/RL/reward-learning-rl/examples/development/main.py", line 66, in _train
    self._build()
  File "/home/ivan/RL/reward-learning-rl/examples/classifier_rl/main.py", line 29, in _build
    env = self.env = get_goal_example_environment_from_variant(variant)
  File "/home/ivan/RL/reward-learning-rl/softlearning/environments/utils.py", line 34, in get_goal_example_environment_from_variant
    return GymAdapter(env=gym.make(variant['task']))
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 84, in make
    env = self._entry_point(**_kwargs)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/__init__.py", line 324, in create_image_48_sawyer_door_pull_hook_v0
    non_presampled_goal_img_is_garbage=True,
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/multiworld/core/image_env.py", line 75, in __init__
    sim = self._wrapped_env.initialize_camera(init_camera)
  File "/home/ivan/anaconda3/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/mujoco_env.py", line 152, in initialize_camera
    viewer = mujoco_py.MjRenderContextOffscreen(sim, device_id=self.device_id)
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

**Comment by leeivan1007** [comment]
I found the problem, well i call:

> env = gym.make('Image48SawyerDoorPullHookEnv-v0')

and the same error is happen.
how did I build 'Image48SawyerDoorPullHookEnv-v0' in my env, have something I miss?

**Comment by avisingh599** [comment]
Can you try running `unset LD_PRELOAD` and then try building the environment again?

**Comment by leeivan1007** [comment]
It can run, think you!!!

**Comment by huiwenzhang** [comment]
@avisingh599  @leeivan1007  Hi, this problem happens because of the contradiction between MjViewer.render() method and MjSim.render() method, as posted in https://github.com/openai/mujoco-py/issues/187 and solved by @vitchyr . But this solution only solves the problem partially, which means you can use either of the method by enable  and  disable the LD_PRELOAD variable. However, if  I need both of these two methods work in a same script, what should I do? This case happens when I create an image based environment and want to render the scene later. I think the image based env like `Image48SawyerDoorPullHookEnv-v0` use kind of  MjSim.render() to initial the camera (call initialize_camera func), but usually the env.render() method is used to render the scene. A simple example is:
```
env = gym.make('Image48SawyerReachXYEnv-v1') # sim.render() used
obs = env.reset()
for _ in range(2000):
    action = env.action_space.sample()
    obs, rew, done, info = env.step(action)
    env.render() # 
    if done:
        env.reset()
```
So in this case,  the problem still exists, right?

**Comment by avisingh599** [comment]
Yeah, I'm not aware of any clean way to use the two different rendering methods at the same time. If you really want to use them both, you could try changing the environment variable [within python](https://stackoverflow.com/questions/5971312/how-to-set-environment-variables-in-python), but it would be a pretty hacky solution.

**Comment by leeivan1007** [comment]
HI~ 
I git clone in new computer with CUAD10.
but it appeared again
`RuntimeError: Failed to initialize OpenGL`
but
`unset LD_PRELOAD`
cann't slove this problem.
and also my old compute (that last time It can run successfully )
create new env, also appeared.
`RuntimeError: Failed to initialize OpenGL`

it is a frustrating thing, I does not find the reason
why it was success last time, and the old env, that successful one can run in the present... 

I think that reason is package.
So I git reset back to 93bb52f, (the time was download the repository)
also can not solve

**Comment by tunglm2203** [comment]
Hi, I also try to install and run your package and face the same problem: `RuntimeError: Failed to initialize OpenGL`
My PC's information:
OS: Ubuntu 16.04
NVIDIA card: GTS 450
CUDA 9.0

I have used the command: `softlearning run_example_debug examples.classifier_rl --n_goal_examples 10 --task=Image48SawyerDoorPullHookEnv-v0 --algorithm VICERAQ --num-samples 1 --n_epochs 300 --active_query_frequency 10`

Here is my error log:
`/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING: Logging before flag parsing goes to stderr.
I0530 21:14:24.598839 139714874894144 __init__.py:34] MuJoCo library version is: 200
Warning: robosuite package not found. Run `pip install robosuite` to use robosuite environments.
I0530 21:14:24.788192 139714874894144 __init__.py:333] Registering multiworld mujoco gym environments
I0530 21:14:26.736764 139714874894144 __init__.py:14] Registering goal example multiworld mujoco gym environments
2019-05-30 21:14:27,255	INFO tune.py:64 -- Did not find checkpoint file in /home/tung/ray_results/multiworld/mujoco/Image48SawyerDoorPullHookEnv-v0/2019-05-30T21-14-27-2019-05-30T21-14-26.
2019-05-30 21:14:27,255	INFO tune.py:211 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/1 GPUs
Memory usage on this node: 2.6/8.2 GB

Using seed 6990
2019-05-30 21:14:27.296322: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-30 21:14:27.485087: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3312000000 Hz
2019-05-30 21:14:27.493785: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x564e003476e0 executing computations on platform Host. Devices:
2019-05-30 21:14:27.493874: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Found 1 GPUs for rendering. Using device 0.
2019-05-30 21:14:29,230	ERROR ray_trial_executor.py:203 -- Error starting runner for Trial a7d5894c-algorithm=VICERAQ-seed=6990
Traceback (most recent call last):
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 201, in start_trial
    self._start_trial(trial, checkpoint)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 143, in _start_trial
    self._train(trial)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 111, in _train
    remote = trial.runner.train.remote()
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 124, in remote
    return self._remote(args, kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 138, in _remote
    num_return_vals=num_return_vals)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 479, in _actor_method_call
    method_name)(*copy.deepcopy(args))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/tung/aim_2019/reward-learning-rl/examples/development/main.py", line 77, in _train
    self._build()
  File "/home/tung/aim_2019/reward-learning-rl/examples/classifier_rl/main.py", line 30, in _build
    get_goal_example_environment_from_variant(variant))
  File "/home/tung/aim_2019/reward-learning-rl/softlearning/environments/utils.py", line 48, in get_goal_example_environment_from_variant
    return GymAdapter(env=gym.make(variant['task']))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 125, in make
    env = spec.make(**kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = self._entry_point(**_kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/__init__.py", line 324, in create_image_48_sawyer_door_pull_hook_v0
    non_presampled_goal_img_is_garbage=True,
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/core/image_env.py", line 75, in __init__
    sim = self._wrapped_env.initialize_camera(init_camera)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/mujoco_env.py", line 152, in initialize_camera
    viewer = mujoco_py.MjRenderContextOffscreen(sim, device_id=self.device_id)
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
2019-05-30 21:14:31,373	INFO ray_trial_executor.py:179 -- Destroying actor for trial a7d5894c-algorithm=VICERAQ-seed=6990. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2019-05-30 21:14:31,454	INFO ray_trial_executor.py:214 -- Trying to start runner for Trial a7d5894c-algorithm=VICERAQ-seed=6990 without checkpoint.
Using seed 6990
Found 1 GPUs for rendering. Using device 0.
2019-05-30 21:14:32,260	ERROR ray_trial_executor.py:219 -- Error starting runner for Trial a7d5894c-algorithm=VICERAQ-seed=6990, aborting!
Traceback (most recent call last):
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 201, in start_trial
    self._start_trial(trial, checkpoint)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 143, in _start_trial
    self._train(trial)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 111, in _train
    remote = trial.runner.train.remote()
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 124, in remote
    return self._remote(args, kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 138, in _remote
    num_return_vals=num_return_vals)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 479, in _actor_method_call
    method_name)(*copy.deepcopy(args))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/tung/aim_2019/reward-learning-rl/examples/development/main.py", line 77, in _train
    self._build()
  File "/home/tung/aim_2019/reward-learning-rl/examples/classifier_rl/main.py", line 30, in _build
    get_goal_example_environment_from_variant(variant))
  File "/home/tung/aim_2019/reward-learning-rl/softlearning/environments/utils.py", line 48, in get_goal_example_environment_from_variant
    return GymAdapter(env=gym.make(variant['task']))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 125, in make
    env = spec.make(**kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = self._entry_point(**_kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/__init__.py", line 324, in create_image_48_sawyer_door_pull_hook_v0
    non_presampled_goal_img_is_garbage=True,
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/core/image_env.py", line 75, in __init__
    sim = self._wrapped_env.initialize_camera(init_camera)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/mujoco_env.py", line 152, in initialize_camera
    viewer = mujoco_py.MjRenderContextOffscreen(sim, device_id=self.device_id)
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 215, in start_trial
    self._start_trial(trial)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 143, in _start_trial
    self._train(trial)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 111, in _train
    remote = trial.runner.train.remote()
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 124, in remote
    return self._remote(args, kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 138, in _remote
    num_return_vals=num_return_vals)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/actor.py", line 479, in _actor_method_call
    method_name)(*copy.deepcopy(args))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/trainable.py", line 151, in train
    result = self._train()
  File "/home/tung/aim_2019/reward-learning-rl/examples/development/main.py", line 77, in _train
    self._build()
  File "/home/tung/aim_2019/reward-learning-rl/examples/classifier_rl/main.py", line 30, in _build
    get_goal_example_environment_from_variant(variant))
  File "/home/tung/aim_2019/reward-learning-rl/softlearning/environments/utils.py", line 48, in get_goal_example_environment_from_variant
    return GymAdapter(env=gym.make(variant['task']))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 183, in make
    return registry.make(id, **kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 125, in make
    env = spec.make(**kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    env = self._entry_point(**_kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/__init__.py", line 324, in create_image_48_sawyer_door_pull_hook_v0
    non_presampled_goal_img_is_garbage=True,
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/core/image_env.py", line 75, in __init__
    sim = self._wrapped_env.initialize_camera(init_camera)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/multiworld/envs/mujoco/mujoco_env.py", line 152, in initialize_camera
    viewer = mujoco_py.MjRenderContextOffscreen(sim, device_id=self.device_id)
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 108, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 128, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
2019-05-30 21:14:32,262	INFO ray_trial_executor.py:179 -- Destroying actor for trial a7d5894c-algorithm=VICERAQ-seed=6990. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
2019-05-30 21:14:32,313	WARNING util.py:62 -- The `start_trial` operation took 5.04341197013855 seconds to complete, which may be a performance bottleneck.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 4/4 CPUs, 0/1 GPUs
Memory usage on this node: 2.7/8.2 GB
Result logdir: /home/tung/ray_results/multiworld/mujoco/Image48SawyerDoorPullHookEnv-v0/2019-05-30T21-14-27-2019-05-30T21-14-26
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - a7d5894c-algorithm=VICERAQ-seed=6990:	ERROR, 2 failures: /home/tung/ray_results/multiworld/mujoco/Image48SawyerDoorPullHookEnv-v0/2019-05-30T21-14-27-2019-05-30T21-14-26/a7d5894c-algorithm=VICERAQ-seed=6990_2019-05-30_21-14-27y8g1efwp/error_2019-05-30_21-14-32.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 4/4 CPUs, 0/1 GPUs
Memory usage on this node: 2.7/8.2 GB
Result logdir: /home/tung/ray_results/multiworld/mujoco/Image48SawyerDoorPullHookEnv-v0/2019-05-30T21-14-27-2019-05-30T21-14-26
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - a7d5894c-algorithm=VICERAQ-seed=6990:	ERROR, 2 failures: /home/tung/ray_results/multiworld/mujoco/Image48SawyerDoorPullHookEnv-v0/2019-05-30T21-14-27-2019-05-30T21-14-26/a7d5894c-algorithm=VICERAQ-seed=6990_2019-05-30_21-14-27y8g1efwp/error_2019-05-30_21-14-32.txt

Traceback (most recent call last):
  File "/home/tung/miniconda2/envs/softlearning/bin/softlearning", line 11, in <module>
    load_entry_point('softlearning', 'console_scripts', 'softlearning')()
  File "/home/tung/aim_2019/reward-learning-rl/softlearning/scripts/console_scripts.py", line 202, in main
    return cli()
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tung/aim_2019/reward-learning-rl/softlearning/scripts/console_scripts.py", line 81, in run_example_debug_cmd
    return run_example_debug(example_module_name, example_argv)
  File "/home/tung/aim_2019/reward-learning-rl/examples/instrument.py", line 254, in run_example_debug
    run_example_local(example_module_name, debug_example_argv, local_mode=True)
  File "/home/tung/aim_2019/reward-learning-rl/examples/instrument.py", line 228, in run_example_local
    reuse_actors=True)
  File "/home/tung/miniconda2/envs/softlearning/lib/python3.6/site-packages/ray/tune/tune.py", line 253, in run
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [a7d5894c-algorithm=VICERAQ-seed=6990])`

**Comment by avisingh599** [comment]
I am not sure what's the reason behind these mujoco-py/opengl errors, since `unset` command usually fixes them for me. I would suggest making an issue in the mujoco-py repository to see if someone there can help resolve your issue: https://github.com/openai/mujoco-py

**Comment by leeivan1007** [comment]
ok ! thank you

**Comment by iparrondo** [comment]
hello , is there a solution to that problem ? 
my myjoco environment work until i installed cuda on my new computer. 
no way to solve this issue with information available on web.

**Comment by Ghiara** [comment]
This works for me:

`self.viewer = mujoco_py.MjRenderContextOffscreen(self.sim, None, device_id=-1) `

`img = self.viewer.read_pixels(512, 512, depth=False)[::-1,:,:]`
