### ISSUE TITLE
Run issue

### ISSUE THREAD

**Issue by fromWRF** [avisingh599/reward-learning-rl#29]
When I run "**softlearning run_example_local examples.classifier_rl --n_goal_examples 10 --task=Image48SawyerDoorPullHookEnv-v0 --algorithm VICERAQ --num-samples 5 --n_epochs 30 --active_query_frequency 10**" . There is a problem:
### **Traceback (most recent call last):
  File "/home/wrf/anaconda3/bin/softlearning", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3253, in <module>
    @_call_aside
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'softlearning' distribution was not found and is required by the application**

**Comment by fromWRF** [comment]
/home/wrf/Desktop/Screenshot from 2020-05-08 19-58-52.png
w

**Comment by fromWRF** [comment]
[/home/wrf/Desktop/Screenshot from 2020-05-08 19-58-52.png](url)

**Comment by fromWRF** [comment]
**(base) wrf@wrf-ThinkPad-E580:~/Documents/Code/reward-learning-rl-master$ softlearning**
In terminal, when i input softlearning, I get the following:
**Traceback (most recent call last):
  File "/home/wrf/anaconda3/bin/softlearning", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3253, in <module>
    @_call_aside
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/wrf/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'softlearning' distribution was not found and is required by the application**

**Comment by avisingh599** [comment]
Can you try doing `pip install -e ${REWARD_LEARNING_PATH}` path and try again?
