### ISSUE TITLE
Cannot Run the Classifier_rl Example

### ISSUE THREAD

**Issue by seekaddo** [avisingh599/reward-learning-rl#35]
**- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04 and 18.04**
**- Python version: 3.6**
**- Requirement.txt file from [link](https://gist.github.com/avisingh599/ec3d67201357a75c01ac1e7a5a8f8369)**
I'm trying to get one of the example module working but i keep getting this error.

```
(softlearning) seekaddo@ubuntu:~/DeepLearning/reward-learning-rl$ conda activate softlearning
(softlearning) seekaddo@ubuntu:~/DeepLearning/reward-learning-rl$ softlearning run_example_local examples.classifier_rl --n_goal_examples 10 --task=Image48SawyerDoorPullHookEnv-v0 --algorithm VICERAQ --num-samples 5 --n_epochs 300 --active_query_frequency 10
2020-12-11 06:19:09.321309: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/seekaddo/.mujoco/mujoco200/bin
2020-12-11 06:19:09.321377: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/seekaddo/miniconda3/envs/softlearning/bin/softlearning", line 11, in <module>
    load_entry_point('softlearning', 'console_scripts', 'softlearning')()
  File "/home/seekaddo/DeepLearning/softlearning/softlearning/scripts/console_scripts.py", line 207, in main
    return cli()
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/seekaddo/DeepLearning/softlearning/softlearning/scripts/console_scripts.py", line 73, in run_example_local_cmd
    return run_example_local(example_module_name, example_argv)
  File "/home/seekaddo/DeepLearning/softlearning/examples/instrument.py", line 222, in run_example_local
    example_module = importlib.import_module(example_module_name)
  File "/home/seekaddo/miniconda3/envs/softlearning/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'examples.classifier_rl'
```

**Comment by seekaddo** [comment]
I thought something want right so i decided to run the classifier_main alone to see if it works and I got this.

```
(softlearning) seekaddo@ubuntu:~/DeepLearning/reward-learning-rl$ python examples/classifier_rl/main.py --help
2020-12-11 06:54:09.645504: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/seekaddo/.mujoco/mujoco200/bin
2020-12-11 06:54:09.645578: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "examples/classifier_rl/main.py", line 11, in <module>
    from softlearning.environments.utils import get_goal_example_environment_from_variant
ImportError: cannot import name 'get_goal_example_environment_from_variant' from 'softlearning.environments.utils' (/home/seekaddo/DeepLearning/softlearning/softlearning/environments/utils.py)
```
